nombre = input ("Digite su nombre: ")
print(type(nombre))
cedula = int(input ("Digite su cedula: "))
print(type(cedula))
peso = float(input ("Digite su peso: "))
print(type(peso))
estado_civil = bool(input(f"Digite su estado civil: estado_civil = True (si esta casado) o False (si no esta casado): "))
print(type(estado_civil))
print (f"Su nombre es: {nombre}, su cedula es: {cedula} y su peso es: {peso} kg y su estado civil es: {estado_civil}")